services:
  client:
    build:
      context: ./client
    ports:
      - 5176:5176
    volumes:
      - ./client:/usr/src/app
  server:
    build:
      context: ./server
    environment:
      NODE_ENV: production
    env_file:
      - ./server/.env
    ports:
      - 5001:5001
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./server:/usr/src/app
  db:
    image: postgres
    restart: always
    volumes:
      - db-data3:/var/lib/postgresql/data
      - ./server:/data
    environment:
      - POSTGRES_USER=glodex
      - POSTGRES_DB=glodex
      - POSTGRES_PASSWORD=glodex
    ports:
      - 5431:5432
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "psql", "-U", "glodex", "-d", "glodex", "-c", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data3:
