INSERT INTO services (name, type, upper_service_id, middle_service_id, created_at, updated_at)
VALUES
  ('Concierge Patient Payments', 'middle', NULL, NULL, NOW(), NOW()),
  ('Concierge Advance', 'lower', NULL, NULL, NOW(), NOW()),
  ('Concierge Per Diem', 'lower', NULL, NULL, NOW(), NOW()),
  ('Concierge Stipend', 'lower', NULL, NULL, NOW(), NOW()),
  ('Concierge Patient Reimbursements', 'middle', NULL, NULL, NOW(), NOW()),
  ('Concierge Accommodations Reimbursement', 'lower', NULL, NULL, NOW(), NOW()),
  ('Concierge Airfare Reimbursement', 'lower', NULL, NULL, NOW(), NOW()),
  ('Concierge Baggage Fee Reimbursement', 'lower', NULL, NULL, NOW(), NOW()),
  ('Concierge Long Term Housing Reimbursement', 'lower', NULL, NULL, NOW(), NOW()),
  ('Concierge Meal Reimbursement', 'lower', NULL, NULL, NOW(), NOW()),
  ('Concierge Medical Expense Reimbursement', 'lower', NULL, NULL, NOW(), NOW()),
  ('Concierge Mileage Reimbursement', 'lower', NULL, NULL, NOW(), NOW()),
  ('Concierge Miscellaneous Reimbursement', 'lower', NULL, NULL, NOW(), NOW()),
  ('Concierge Parking & Tolls Reimbursement', 'lower', NULL, NULL, NOW(), NOW()),
  ('Concierge Rail/Train/Bus Reimbursement', 'lower', NULL, NULL, NOW(), NOW()),
  ('Concierge Rental Car & Gas Reimbursement', 'lower', NULL, NULL, NOW(), NOW()),
  ('Concierge Taxi & Rideshare Reimbursement', 'lower', NULL, NULL, NOW(), NOW()),
  ('Concierge Wage Reimbursement', 'lower', NULL, NULL, NOW(), NOW()),
  ('Concierge Travel Services', 'middle', NULL, NULL, NOW(), NOW()),
  ('Concierge Air', 'lower', NULL, NULL, NOW(), NOW()),
  ('Concierge Car Service', 'lower', NULL, NULL, NOW(), NOW()),
  ('Concierge Local Taxi', 'lower', NULL, NULL, NOW(), NOW()),
  ('Concierge Rail', 'lower', NULL, NULL, NOW(), NOW()),
  ('Concierge Rental Car', 'lower', NULL, NULL, NOW(), NOW()),
  ('Concierge Bus', 'lower', NULL, NULL, NOW(), NOW()),
  ('Concierge Ferry', 'lower', NULL, NULL, NOW(), NOW()),
  ('Concierge Hotel', 'lower', NULL, NULL, NOW(), NOW()),
  ('Concierge Rideshare', 'lower', NULL, NULL, NOW(), NOW()),
  ('Concierge WAV Car Service', 'lower', NULL, NULL, NOW(), NOW()),
  ('Special Services', 'middle', NULL, NULL, NOW(), NOW()),
  ('WAV Rental Car', 'lower', NULL, NULL, NOW(), NOW()),
  ('Air Ambulance', 'lower', NULL, NULL, NOW(), NOW()),
  ('Private Charter', 'lower', NULL, NULL, NOW(), NOW()),
  ('Emergency Medical Support', 'lower', NULL, NULL, NOW(), NOW()),
  ('Non-Emergency Vehicle Support', 'lower', NULL, NULL, NOW(), NOW()),
  ('Home Health', 'lower', NULL, NULL, NOW(), NOW()),
  ('Long Term Housing', 'lower', NULL, NULL, NOW(), NOW()),
  ('Passport Services', 'lower', NULL, NULL, NOW(), NOW()),
  ('Non-emergency Medical Support', 'lower', NULL, NULL, NOW(), NOW()),
  ('Medical Insurance', 'lower', NULL, NULL, NOW(), NOW()),
  ('Moving Services', 'lower', NULL, NULL, NOW(), NOW()),
  ('Relocation Services', 'lower', NULL, NULL, NOW(), NOW()),
  ('Transfer of Medical Personnel', 'lower', NULL, NULL, NOW(), NOW()),
  ('Traveling with Controlled Substances', 'lower', NULL, NULL, NOW(), NOW()),
  ('Shipping Services', 'lower', NULL, NULL, NOW(), NOW()),
  ('Specialty Services', 'lower', NULL, NULL, NOW(), NOW()),
  ('Translation Services', 'lower', NULL, NULL, NOW(), NOW()),
  ('Travel Insurance', 'lower', NULL, NULL, NOW(), NOW()),
  ('Specimen Shipment', 'lower', NULL, NULL, NOW(), NOW()),
  ('Visa/Immigration Services', 'lower', NULL, NULL, NOW(), NOW()),
  ('Amazon Purchasing', 'lower', NULL, NULL, NOW(), NOW()),
  ('Medical Equipment Rental', 'lower', NULL, NULL, NOW(), NOW()),
  ('Other Specialty Service', 'lower', NULL, NULL, NOW(), NOW()),
  ('Premium Patient Payments', 'middle', NULL, NULL, NOW(), NOW()),
  ('Premium Advance', 'lower', NULL, NULL, NOW(), NOW()),
  ('Premium Per Diem', 'lower', NULL, NULL, NOW(), NOW()),
  ('Premium Stipend', 'lower', NULL, NULL, NOW(), NOW()),
  ('Premium Patient Reimbursements', 'lower', NULL, NULL, NOW(), NOW()),
  ('Premium Accommodations Reimbursement', 'lower', NULL, NULL, NOW(), NOW()),
  ('Premium Airfare Reimbursement', 'lower', NULL, NULL, NOW(), NOW()),
  ('Premium Baggage Fee Reimbursement', 'lower', NULL, NULL, NOW(), NOW()),
  ('Premium Long Term Housing Reimbursement', 'lower', NULL, NULL, NOW(), NOW()),
  ('Premium Meal Reimbursement', 'lower', NULL, NULL, NOW(), NOW()),
  ('Premium Medical Expense Reimbursement', 'lower', NULL, NULL, NOW(), NOW()),
  ('Premium Mileage Reimbursement', 'lower', NULL, NULL, NOW(), NOW()),
  ('Premium Miscellaneous Reimbursement', 'lower', NULL, NULL, NOW(), NOW()),
  ('Premium Parking & Tolls Reimbursement', 'lower', NULL, NULL, NOW(), NOW()),
  ('Premium Rail/Train/Bus Reimbursement', 'lower', NULL, NULL, NOW(), NOW()),
  ('Premium Rental Car & Gas Reimbursement', 'lower', NULL, NULL, NOW(), NOW()),
  ('Premium Taxi & Rideshare Reimbursement', 'lower', NULL, NULL, NOW(), NOW()),
  ('Premium Wage Reimbursement', 'lower', NULL, NULL, NOW(), NOW()),
  ('Premium Travel Services', 'middle', NULL, NULL, NOW(), NOW()),
  ('Premium Air', 'lower', NULL, NULL, NOW(), NOW()),
  ('Premium Car Service', 'lower', NULL, NULL, NOW(), NOW()),
  ('Premium Local Taxi', 'lower', NULL, NULL, NOW(), NOW()),
  ('Premium Rail', 'lower', NULL, NULL, NOW(), NOW()),
  ('Premium Rental Car', 'lower', NULL, NULL, NOW(), NOW()),
  ('Premium Bus', 'lower', NULL, NULL, NOW(), NOW()),
  ('Premium Ferry', 'lower', NULL, NULL, NOW(), NOW()),
  ('Premium Hotel', 'lower', NULL, NULL, NOW(), NOW()),
  ('Premium Rideshare', 'lower', NULL, NULL, NOW(), NOW()),
  ('Premium WAV Car Service', 'lower', NULL, NULL, NOW(), NOW()),
  ('Standard Patient Payments', 'middle', NULL, NULL, NOW(), NOW()),
  ('Standard Advance', 'lower', NULL, NULL, NOW(), NOW()),
  ('Standard Per Diem', 'lower', NULL, NULL, NOW(), NOW()),
  ('Standard Stipend', 'lower', NULL, NULL, NOW(), NOW()),
  ('Standard Patient Reimbursements', 'lower', NULL, NULL, NOW(), NOW()),
  ('Standard Accommodations Reimbursement', 'lower', NULL, NULL, NOW(), NOW()),
  ('Standard Airfare Reimbursement', 'lower', NULL, NULL, NOW(), NOW()),
  ('Standard Baggage Fee Reimbursement', 'lower', NULL, NULL, NOW(), NOW()),
  ('Standard Long Term Housing Reimbursement', 'lower', NULL, NULL, NOW(), NOW()),
  ('Standard Meal Reimbursement', 'lower', NULL, NULL, NOW(), NOW()),
  ('Standard Medical Expense Reimbursement', 'lower', NULL, NULL, NOW(), NOW()),
  ('Standard Mileage Reimbursement', 'lower', NULL, NULL, NOW(), NOW()),
  ('Standard Miscellaneous Reimbursement', 'lower', NULL, NULL, NOW(), NOW()),
  ('Standard Parking & Tolls Reimbursement', 'lower', NULL, NULL, NOW(), NOW()),
  ('Standard Rail/Train/Bus Reimbursement', 'lower', NULL, NULL, NOW(), NOW()),
  ('Standard Rental Car & Gas Reimbursement', 'lower', NULL, NULL, NOW(), NOW()),
  ('Standard Taxi & Rideshare Reimbursement', 'lower', NULL, NULL, NOW(), NOW()),
  ('Standard Wage Reimbursement', 'lower', NULL, NULL, NOW(), NOW()),
  ('Standard Travel Services', 'middle', NULL, NULL, NOW(), NOW()),
  ('Standard Air', 'lower', NULL, NULL, NOW(), NOW()),
  ('Standard Car Service', 'lower', NULL, NULL, NOW(), NOW()),
  ('Standard Local Taxi', 'lower', NULL, NULL, NOW(), NOW()),
  ('Standard Rail', 'lower', NULL, NULL, NOW(), NOW()),
  ('Standard Rental Car', 'lower', NULL, NULL, NOW(), NOW()),
  ('Standard Bus', 'lower', NULL, NULL, NOW(), NOW()),
  ('Standard Ferry', 'lower', NULL, NULL, NOW(), NOW()),
  ('Standard Hotel', 'lower', NULL, NULL, NOW(), NOW()),
  ('Standard Rideshare', 'lower', NULL, NULL, NOW(), NOW()),
  ('Standard WAV Car Service', 'lower', NULL, NULL, NOW(), NOW()),
  ('Payment Methods', 'middle', NULL, NULL, NOW(), NOW()),
  ('Prepaid Cards', 'lower', NULL, NULL, NOW(), NOW()),
  ('Local Bank Transfer', 'lower', NULL, NULL, NOW(), NOW()),
  ('SWIFT Bank Transfer', 'lower', NULL, NULL, NOW(), NOW()),
  ('Mobile Wallet', 'lower', NULL, NULL, NOW(), NOW()),
  ('Push to Card', 'lower', NULL, NULL, NOW(), NOW()),
  ('Participant Travel Management', 'middle', NULL, NULL, NOW(), NOW()),
  ('Itinerary Views', 'lower', NULL, NULL, NOW(), NOW()),
  ('Rideshare Views', 'lower', NULL, NULL, NOW(), NOW()),
  ('Financial Information Views', 'lower', NULL, NULL, NOW(), NOW()),
  ('Receipt Submission', 'lower', NULL, NULL, NOW(), NOW()),
  ('Mobile Engagement', 'middle', NULL, NULL, NOW(), NOW()),
  ('Surveys', 'lower', NULL, NULL, NOW(), NOW()),
  ('Insights', 'lower', NULL, NULL, NOW(), NOW()),
  ('Medication Management', 'lower', NULL, NULL, NOW(), NOW()),
  ('Help Desk', 'lower', NULL, NULL, NOW(), NOW()),
  ('Financial Management', 'upper', NULL, NULL, NOW(), NOW()),
  ('Site Payments', 'middle', NULL, NULL, NOW(), NOW()),
  ('Budget Development', 'middle', NULL, NULL, NOW(), NOW()),
  ('Analytics & Insights', 'upper', NULL, NULL, NOW(), NOW()),
  ('Registry Services', 'middle', NULL, NULL, NOW(), NOW()),
  ('Registry Surveys', 'lower', NULL, NULL, NOW(), NOW()),
  ('Registry Trackers', 'lower', NULL, NULL, NOW(), NOW()),
  ('Registry Test Results', 'lower', NULL, NULL, NOW(), NOW()),
  ('Consulting', 'middle', NULL, NULL, NOW(), NOW()),
  ('Data Services', 'middle', NULL, NULL, NOW(), NOW()),
  ('Data Collection', 'lower', NULL, NULL, NOW(), NOW()),
  ('Data Reporting', 'lower', NULL, NULL, NOW(), NOW()),
  ('Payment Rules Engine', 'lower', NULL, NULL, NOW(), NOW());
